import type { ExpensePlan, ScheduleItem } from "./types";

export const INITIAL_PLANS: ExpensePlan[] = [
  {
    id: "design-outsourcing",
    name: "UI 디자인 외주 제작",
    purpose: "MVP 서비스의 사용자 화면 설계와 디자인 시스템 제작",
    amount: 3000000,
    plannedDate: "2026-09-30",
    category: "외주용역비",
    vendor: "스튜디오 모노",
    status: "확인 필요",
    nextAction: "계약 범위 확인",
    updatedAt: "2026.08.24 11:20",
    aiSummary: "외주 과업과 사업계획의 연관성은 확인됐습니다. 계약 전 과업 범위, 결과물, 검수 기준을 문서로 명확히 해야 합니다.",
    aiChecks: [
      { id: "scope", label: "과업 범위 확정", description: "화면 수, 산출물 형식, 수정 횟수를 계약서에 기재하세요." },
      { id: "quote", label: "금액 적정성 확인", description: "견적과 비교자료로 금액 산출 근거를 준비하세요." },
      { id: "conflict", label: "특수관계 여부 확인", description: "대표자·팀원과 거래처의 이해관계를 확인하세요." },
    ],
    evidence: [
      { id: "contract", label: "계약서", description: "과업 범위와 검수 조건 포함" },
      { id: "task", label: "과업내용서", description: "세부 작업과 결과물 명시" },
      { id: "estimate", label: "견적서·비교자료", description: "금액 적정성 확인 자료" },
      { id: "result", label: "결과보고서·검수자료", description: "집행 후 등록" },
    ],
    rules: [
      { title: "사업 목적과의 직접 관련성", source: "2026 초기창업패키지 사업화 자금 공통 기준", description: "외주 결과물이 사업계획의 제품·서비스 개발에 직접 활용되는지 확인합니다." },
      { title: "참여기관 세부 집행기준", source: "선정기관 사업비 집행 안내", description: "계약 금액별 비교견적·사전확인 요건은 참여기관의 최신 안내를 추가로 적용합니다." },
    ],
  },
  {
    id: "notebook",
    name: "개발용 노트북 구매",
    purpose: "서비스 프론트엔드 개발과 홍보영상 편집을 위한 전용 장비",
    amount: 2200000,
    plannedDate: "2026-09-18",
    category: "기계장치비",
    vendor: "애플코리아",
    status: "확인 필요",
    nextAction: "구매 필요성 보완",
    updatedAt: "2026.08.24 10:05",
    aiSummary: "개발·콘텐츠 제작 목적은 확인됐습니다. 범용성 기자재로 볼 수 있어 사용자, 기존 보유 장비, 구매 필요성을 구체적으로 남겨야 합니다.",
    aiChecks: [
      { id: "user", label: "실사용자 확인", description: "대표자 또는 참여 인력 중 실제 사용자를 지정하세요." },
      { id: "owned", label: "기존 장비 보유 여부", description: "사업비로 구매한 기존 PC·노트북이 있는지 확인하세요." },
      { id: "need", label: "사업 직접 필요성 작성", description: "일반 사무용이 아닌 개발·제작 사양이 필요한 이유를 작성하세요." },
    ],
    evidence: [
      { id: "need-doc", label: "구매 필요성 자료", description: "업무·사양과의 연결 설명" },
      { id: "estimate", label: "견적서·비교자료", description: "모델과 가격 비교" },
      { id: "transaction", label: "거래명세서", description: "모델·수량·단가 확인" },
      { id: "photo", label: "물품 사진·검수자료", description: "집행 후 등록" },
    ],
    rules: [
      { title: "범용성 기자재 판단", source: "2026 초기창업패키지 사업화 자금 공통 기준", description: "노트북은 사업 수행에 직접 필요한 사유와 전용 사용 여부를 중심으로 확인합니다." },
      { title: "기관별 사전절차", source: "선정기관 사업비 집행 안내", description: "구매 금액과 품목에 따른 승인·자산관리 절차는 기관 기준을 확인해야 합니다." },
    ],
  },
  {
    id: "research-meeting",
    name: "시장조사 인터뷰 회의비",
    purpose: "잠재고객 4명 대상 서비스 사용성 인터뷰 진행",
    amount: 120000,
    plannedDate: "2026-09-12",
    category: "회의비",
    vendor: "카페 브릭",
    status: "위험",
    nextAction: "1인 단가 확인",
    updatedAt: "2026.08.23 16:30",
    aiSummary: "참석자 4명 기준 1인당 30,000원으로 계산됩니다. 기관의 1인 단가 기준을 초과할 수 있으므로 결제 전에 금액 조정이 필요합니다.",
    aiChecks: [
      { id: "attendee", label: "참석자와 인원 확정", description: "내부·외부 참석자를 구분해 명단을 작성하세요." },
      { id: "agenda", label: "회의 목적과 안건 작성", description: "사업 수행과 직접 관련된 인터뷰 안건을 남기세요." },
      { id: "limit", label: "기관 1인 단가 확인", description: "현재 예상 단가 30,000원의 허용 여부를 확인하세요." },
    ],
    evidence: [
      { id: "minutes", label: "회의록", description: "일시·장소·안건·결과 포함" },
      { id: "attendee-list", label: "참석자 명단", description: "소속과 서명 등 기관 양식 확인" },
      { id: "receipt", label: "카드영수증", description: "집행 일시와 금액 확인" },
    ],
    rules: [
      { title: "회의 목적과 참석자", source: "2026 초기창업패키지 사업화 자금 공통 기준", description: "사업 수행을 위한 회의인지, 참석자와 집행 금액이 타당한지 확인합니다." },
      { title: "회의비 단가", source: "선정기관 사업비 집행 안내", description: "1인 단가와 외부 참석자 요건은 기관의 최신 기준을 우선 확인합니다." },
    ],
  },
  {
    id: "online-ad",
    name: "서비스 출시 온라인 광고",
    purpose: "MVP 출시 후 타깃 고객 유입과 전환 데이터 확보",
    amount: 800000,
    plannedDate: "2026-10-05",
    category: "광고선전비",
    vendor: "메타 플랫폼",
    status: "특이사항 없음",
    nextAction: "집행 일정 등록",
    updatedAt: "2026.08.22 14:10",
    aiSummary: "사업계획의 고객 검증·마케팅 활동과 직접 관련된 지출로 확인됩니다. 캠페인 기간과 결과 증빙을 보관하면 됩니다.",
    aiChecks: [
      { id: "period", label: "캠페인 기간 확인", description: "사업기간 내 광고 노출과 결제가 완료되는지 확인하세요.", done: true },
      { id: "target", label: "타깃·목표 설정", description: "대상 고객과 성과지표를 작성하세요.", done: true },
      { id: "account", label: "광고 계정 확인", description: "사업자 또는 팀 명의의 계정을 사용하세요.", done: true },
    ],
    evidence: [
      { id: "statement", label: "광고 결제내역", description: "기간·금액·결제수단 확인" },
      { id: "capture", label: "광고 게재 화면", description: "소재와 노출 기간 확인" },
      { id: "report", label: "캠페인 결과자료", description: "도달·클릭·전환 결과" },
    ],
    rules: [
      { title: "사업화 목적의 홍보", source: "2026 초기창업패키지 사업화 자금 공통 기준", description: "제품·서비스의 시장 진입과 고객 확보를 위한 홍보인지 확인합니다." },
    ],
  },
  {
    id: "camera",
    name: "제품 촬영용 카메라 구매",
    purpose: "제품 상세페이지와 홍보 콘텐츠 상시 제작",
    amount: 1500000,
    plannedDate: "2026-09-26",
    category: "기계장치비",
    vendor: "소니 스토어",
    status: "확인 필요",
    nextAction: "임차 대안 비교",
    updatedAt: "2026.08.21 17:05",
    aiSummary: "홍보 콘텐츠 제작 목적은 확인됐지만 범용 장비로 활용될 가능성이 있습니다. 구매와 임차 중 경제성을 비교하고 상시 활용 계획을 보완하세요.",
    aiChecks: [
      { id: "use", label: "상시 활용 계획", description: "촬영 횟수와 제작 콘텐츠를 구체화하세요." },
      { id: "rental", label: "임차 대안 비교", description: "동일 기간 임차 비용과 구매 비용을 비교하세요." },
      { id: "manager", label: "보관·관리자 지정", description: "장비 보관 장소와 관리 책임자를 지정하세요." },
    ],
    evidence: [
      { id: "estimate", label: "견적서·비교자료", description: "구매·임차 대안 포함" },
      { id: "need", label: "구매 필요성 자료", description: "콘텐츠 제작 계획 연결" },
      { id: "serial", label: "제품·시리얼 사진", description: "집행 후 자산 확인" },
      { id: "inspection", label: "검수자료", description: "수령·작동 확인" },
    ],
    rules: [
      { title: "장비 구매 필요성", source: "2026 초기창업패키지 사업화 자금 공통 기준", description: "사업 목적과의 직접 관련성, 구매 경제성, 전용 활용 여부를 확인합니다." },
      { title: "자산 관리", source: "선정기관 사업비 집행 안내", description: "자산 등록과 보관 기준은 참여기관의 절차를 적용합니다." },
    ],
  },
  {
    id: "mentoring",
    name: "브랜드 전략 멘토링",
    purpose: "시장 포지셔닝과 출시 메시지 정교화를 위한 전문가 자문",
    amount: 1200000,
    plannedDate: "2026-10-12",
    category: "지급수수료·멘토링",
    vendor: "브랜드랩 김OO",
    status: "확인 필요",
    nextAction: "전문성 자료 준비",
    updatedAt: "2026.08.20 10:22",
    aiSummary: "멘토링 주제는 사업계획과 연결됩니다. 멘토 전문성, 회차별 자문 내용, 결과물을 확인할 수 있는 자료가 필요합니다.",
    aiChecks: [
      { id: "expert", label: "멘토 전문성 확인", description: "경력과 자문 분야를 확인할 자료를 준비하세요." },
      { id: "scope", label: "회차별 자문 범위", description: "일정·시간·주제·결과물을 사전에 정리하세요." },
      { id: "rate", label: "자문료 기준 확인", description: "기관의 지급 기준과 원천징수 여부를 확인하세요." },
    ],
    evidence: [
      { id: "profile", label: "전문가 이력", description: "경력·전문 분야 확인" },
      { id: "plan", label: "멘토링 계획서", description: "회차·시간·주제 포함" },
      { id: "report", label: "자문 결과보고서", description: "회차별 논의와 결과" },
      { id: "payment", label: "지급·세무 증빙", description: "수령 형태에 맞는 자료" },
    ],
    rules: [
      { title: "전문가 활용의 필요성", source: "2026 초기창업패키지 사업화 자금 공통 기준", description: "자문이 사업 수행에 필요하고 전문가의 역량과 과업이 적정한지 확인합니다." },
      { title: "자문료 지급 기준", source: "선정기관 사업비 집행 안내", description: "지급 한도, 원천징수, 제출 서류는 기관별 기준을 확인합니다." },
    ],
  },
];

export const INITIAL_SCHEDULES: ScheduleItem[] = [
  { id: "s1", planId: "research-meeting", title: "회의비 단가 확인", date: "2026-09-09", type: "기타", state: "준비 필요" },
  { id: "s5", planId: "design-outsourcing", title: "계약 협의 확인", date: "2026-09-13", type: "계약", state: "준비 필요" },
  { id: "s2", planId: "notebook", title: "구매 필요성·비교자료 준비", date: "2026-09-14", type: "비교견적", state: "준비 필요" },
  { id: "s6", planId: "design-outsourcing", title: "외주 계약 사전 준비", date: "2026-09-15", type: "계약", state: "예정" },
  { id: "s7", planId: "camera", title: "구매 필요성 보완", date: "2026-09-16", type: "기타", state: "준비 필요" },
  { id: "s8", planId: "research-meeting", title: "1인 단가 협의", date: "2026-09-19", type: "기타", state: "준비 필요" },
  { id: "s3", planId: "design-outsourcing", title: "외주 계약 범위 확정", date: "2026-09-22", type: "계약", state: "예정" },
  { id: "s9", planId: "notebook", title: "구매 필요성 보완", date: "2026-09-30", type: "기타", state: "완료" },
  { id: "s4", planId: "online-ad", title: "온라인 광고 집행", date: "2026-10-05", type: "집행", state: "예정" },
];
